name: CMake Linux build clang-18
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup
        run: |
          sudo apt install -y clang-18 libgtest-dev libstdc++-14-dev libc++-dev libc++abi-dev make cmake libpython3-dev libomp-dev
      - name: Prepare
        env:
          CXXFLAGS: -O2
          CC: clang-18
          CXX: clang++-18
        run: |
          export CWD=$PWD
          mkdir gtest
          cp -r /usr/src/gtest/* gtest/
          cd gtest
          cmake CMakeLists.txt -DCMAKE_CXX_FLAGS="$CXX_FLAGS"
          make
          sudo cp *.* /usr/lib/
          cd $CWD
      - name: Compile
        env:
          CXXFLAGS: -O2
          CC: clang-18
          CXX: clang++-18
        run: |
          bash -e ./build_linux.sh